Update pubbun.yml

diff --git a/.github/workflows/pubbun.yml b/.github/workflows/pubbun.yml
--- a/.github/workflows/pubbun.yml
+++ b/.github/workflows/pubbun.yml
@@ -67,23 +67,23 @@ jobs:
           ssh-add /tmp/ssh_key
           ssh-keyscan -H "$SSH_ADDR" >> ~/.ssh/known_hosts
           ssh-add -l
-      - name: Restart Server Service
-        run: |
-          ssh -i /tmp/ssh_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no "$SSH_USER@$SSH_ADDR" << 'EOF'
-            # Replace 'your-service-name' with the actual service name
-            SERVICE="web"
-            if systemctl is-active --quiet "$SERVICE"; then
-              echo "Service $SERVICE is running. Stopping it..."
-              sudo systemctl stop "$SERVICE"
-            else
-              echo "Service $SERVICE is not running."
-            fi
-            echo "Starting $SERVICE..."
-            sudo systemctl start "$SERVICE"
-            if systemctl is-active --quiet "$SERVICE"; then
-              echo "Service $SERVICE restarted successfully."
-            else
-              echo "Failed to restart $SERVICE."
-              exit 1
-            fi
-          EOF
+          - name: Restart Remote Service
+            run: |
+              ssh -i /tmp/ssh_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no "$SSH_USER@$SSH_ADDR" << EOF
+                # Replace 'your-service-name' with the actual service name
+                SERVICE="web"
+                if systemctl is-active --quiet "$SERVICE"; then
+                  echo "Service $SERVICE is running. Stopping it..."
+                  sudo systemctl stop "$SERVICE"
+                else
+                  echo "Service $SERVICE is not running."
+                fi
+                echo "Starting $SERVICE..."
+                sudo systemctl start "$SERVICE"
+                if systemctl is-active --quiet "$SERVICE"; then
+                  echo "Service $SERVICE restarted successfully."
+                else
+                  echo "Failed to restart $SERVICE."
+                  exit 1
+                fi
+              EOF
